name: Firebase hosting

on:
  push:
    branches: [ master, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Install firebase tools
      run: |
        sudo npm install -g firebase-tools
        firebase use lzz-personalblog --token ${{ secrets.FIREBASE_TOKEN }}

    - name: Build website
      run: |
        yarn
        yarn build
        
    - name: Deploy to staging site
      if: github.ref == 'refs/heads/staging'
      run: firebase deploy --only hosting:staging --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "${{ github.event.head_commit.message }}"
      
    - name: Deploy to production site
      if: github.ref == 'refs/heads/master'
      run: firebase deploy --only hosting:prod --non-interactive --token ${{ secrets.FIREBASE_TOKEN }} -m "${{ github.event.head_commit.message }}"

    - name: Archive build Artifact
      uses: actions/upload-artifact@master
      with:
        path: build
