name: Firebase hosting

on:
  push:
    branches: [ master, staging ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    - name: Build website
      run: |
        yarn
        yarn build
        
    - name: Deploy to staging site
      if: github.ref == 'refs/heads/staging'
      uses: lowply/deploy-firebase@v0.0.2
      with:
        args: deploy --only hosting:staging --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: lzz-personalblog
      
    - name: Deploy to production site
      if: github.ref == 'refs/heads/master'
      uses: lowply/deploy-firebase@v0.0.2
      with:
        args: deploy --only hosting:prod --non-interactive
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        FIREBASE_PROJECT: lzz-personalblog

    - name: Archive build Artifact
      uses: actions/upload-artifact@master
      with:
        path: build
